// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFqb9i4cIBd_6FK1nwBpUE3nJZVWpD3Mw',
    appId: '1:577984434584:web:eaf91524d9641240c6dbed',
    messagingSenderId: '577984434584',
    projectId: 'smartwatch-669b1',
    authDomain: 'smartwatch-669b1.firebaseapp.com',
    databaseURL: 'https://smartwatch-669b1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartwatch-669b1.firebasestorage.app',
    measurementId: 'G-WX9SCCYTKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAODlQ26fMfFy8lBKMobhKcdK7YCD9pw',
    appId: '1:577984434584:android:343fa4c210b39505c6dbed',
    messagingSenderId: '577984434584',
    projectId: 'smartwatch-669b1',
    databaseURL: 'https://smartwatch-669b1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartwatch-669b1.firebasestorage.app',
  );
}
